services:
  www:
    build: . #va chercher le .dockerfile dans lequel on installe l'image de php + mysqli
    volumes:
      - "./:/var/www/html" #sync project dir with the container web dir. ./ means "file you are currently in"
    ports:
      - '80:80'     # apache
      - '443:443'   # for future ssl traffic
    depends_on:
      - db
    env_file:
      - .env  # link the env file


  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
      - CHARSET=${CHARSET}
    volumes:
      - './db:/docker-entrypoint-initdb.d' #sync persistent sql files with container
    env_file:
      - .env  # link the env file
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    env_file:
      - .env  # link the env file 